### ISSUE TITLE
[错误] 登录界面点击输入框后，底部按钮显示不正常

### ISSUE THREAD

**Issue by TimHXL** [fhraise/Fhraise#25]
### 错误类型

界面错误

### 平台

Android

### 版本

v0.1.82

### 环境

操作系统：Android 10；设备：HUAWEI MATE 20

### 错误

当我点击登录界面的输入手机号框时，底部更多登录选项的按钮会浮到键盘上面，挡住了输入手机号码的输入框。点击界面的其他地方之后又恢复正常显示

### 可能的解决方案

按钮应用的边距中，取消键盘高度，可能会解决此问题。

### 截图或视频

![Screenshot_20240128_184950_xyz xfqlittlefan fhraise](https://github.com/fhraise/Fhraise/assets/121989148/ca36c4a3-da24-4a62-abe4-ba88b4c4f419)

### 联系方式

TimHXL01@gmail.com

**Comment by xfqwdsj** [comment]
#27
